### ISSUE TITLE
Failed to exec deploy-storybook script

### ISSUE THREAD

**Issue by jessepinuelas** [storybookjs/storybook-deployer#103]
**Describe the bug**
No longer able to deploy to GH Pages after updating to react-scripts 4.0.1 Previously I was able to simply run **npm run deploy-storybook**. Now when running the deploy command it fails when building -storybook. **It fails at 92% of build process on chunk asset optimization TerserPlugin**.

**To Reproduce**
Using react-scripts 3.4.4 **storybook build correctly**
Updating to react-scripts 4.0.1 **storybook build fails** which also prevents deploying to gh pages

**Expected behavior**
Successfully builds and deploys updates to GH Pages

**System**
OS: macOS 10.15.6
CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

**Binaries:**
Node: 12.12.0 - ~/.nvm/versions/node/v12.12.0/bin/node
npm: 6.11.3 - ~/.nvm/versions/node/v12.12.0/bin/npm

**npmPackages:**
@storybook/addon-actions: 6.1.21 => 6.1.21
@storybook/addon-essentials: 6.1.21 => 6.1.21
@storybook/addon-links: 6.1.21 => 6.1.21
@storybook/addons: 6.1.21 => 6.1.21
@storybook/node-logger: 6.1.21 => 6.1.21
@storybook/preset-create-react-app: 3.1.7 => 3.1.7
@storybook/react: 6.1.21 => 6.1.21
@storybook/storybook-deployer: 2.8.7 => 2.8.7
@storybook/theming: 6.1.21 => 6.1.21

**Additional context**
`  _lastActiveSortFn: undefined,
ERR!       _sortFn: undefined,
ERR!       _cache: undefined,
ERR!       _cacheOrderIndependent: undefined
ERR!     },
ERR!     contextDependencies: SortableSet [Set] {
ERR!       '/Users/private-user/private-repo/src',
ERR!       _sortFn: undefined,
ERR!       _lastActiveSortFn: null,
ERR!       _cache: undefined,
ERR!       _cacheOrderIndependent: undefined
ERR!     },
ERR!     missingDependencies: SortableSet [Set] {
ERR!       _sortFn: undefined,
ERR!       _lastActiveSortFn: null,
ERR!       _cache: undefined,
ERR!       _cacheOrderIndependent: undefined
ERR!     }
ERR!   },
ERR!   hash: '82b3f88322128a30b9ea',
ERR!   startTime: 1616717641781,
ERR!   endTime: 1616717683706
ERR! }
`

**Comment by Sutikshan** [comment]
Hey @jessepinuelas How did you fix this error?

**Comment by Tjedor** [comment]
@jessepinuelas Hi, I am facing the same problem, do you have any solution to the problem?
