### ISSUE TITLE
[Bug] Critical vulnerability in due to outdated dependency `git-url-parse`

### ISSUE THREAD

**Issue by siminino** [storybookjs/storybook-deployer#124]
### Describe the bug

Critical vulnerability related to `git-url-parse` sub dependency `parse-url`. It is not possible to fix it in my projects by yarn resolutions since is related to major version upgrades containing Breaking Changes. To fix it, `git-url-parse` must be upgraded to version 12.

Obs: also high and moderate vulnerabilities are going to be fixed by this dependency upgrade.

### Steps to reproduce the behaviour

1. clone repo;
2. run `yarn`;
4. run `yarn audit`;

### Expected behaviour

No critical and high vulnerabilities.

### Screenshots and/or logs

<img width="668" alt="Screenshot 2022-07-15 at 12 20 05" src="https://user-images.githubusercontent.com/632044/179205036-1b726fc4-92eb-458b-8bd1-5f95b0c411f7.png">

<img width="450" alt="Screenshot 2022-07-15 at 12 29 00" src="https://user-images.githubusercontent.com/632044/179205981-80842ec2-0957-4b86-afff-073886aee7a9.png">

### Environment

 - Node.js version: v16.13.1
 - NPM version: 8.1.2

**Comment by cysp** [comment]
Great to see that this dependency update was merged a few weeks ago! 👏 
@jimmyandrade is there an upcoming release scheduled that will include that change?

**Comment by pjaws** [comment]
3 weeks later and still no release... Storybook is currently responsible for every single vulnerability in my project.

**Comment by nedredmond** [comment]
@cysp @pjaws it looks like this may have been deployed on NPM but it is not reflected on GitHub:
https://www.npmjs.com/package/@storybook/storybook-deployer

see the thread here:
https://github.com/storybookjs/storybook-deployer/pull/127

**Comment by pjaws** [comment]
@nedredmond My apologies, there is a [separate vulnerability](https://github.com/advisories/GHSA-j9fq-vwqv-2fm2) in `parse-url` via `git-parse-url` that is also a SSRF vulnerability. This is fixed in `git-url-parse` version 13+. I think this might be where the confusion is coming from.

**Comment by nedredmond** [comment]
I see. [Well, at least the fix for _this_ issue with a bump to v12 was released on NPM](https://app.renovatebot.com/package-diff?name=@storybook/storybook-deployer&from=2.8.12&to=2.8.16). It looks like the GitHub release info on the repo isn't synced. I thought that might have thrown off dependabot. I guess I dismissed that alert too early. :face_exhaling:

**Comment by nedredmond** [comment]
https://github.com/storybookjs/storybook-deployer/pull/131
