### ISSUE TITLE
Could not read username for enterprise github

### ISSUE THREAD

**Issue by daituzhang** [storybookjs/storybook-deployer#33]
Hi team, 
Thank you for building this awesome library.
I'm trying to use it for enterprise github by using the github api token in jenkins pipeline.
I've set up the user name in `package.json`
```
"storybook-deployer": {
    "gitUsername": "testName",
    "gitEmail": "testEmail",
    "commitMessage": "Deploy Storybook [skip ci]"
  }
```
And I got error below
```
> storybook-to-ghpages "--ci" "--host-token-env-variable=****"

=> Getting the git remote URL
   executing: git config --get remote.origin.url
=> Building storybook
   executing: node ./node_modules/.bin/build-storybook -o out2263
   executing: git init
   executing: git config user.name "testName"
   executing: git config user.email "testEmail"
   executing: git config commit.gpgsign false
   executing: git add .
   executing: git commit -m "Deploy Storybook [skip ci]"
=> Deploying storybook
   executing: git push --force --quiet https://github.enterprisename.com/testName/XXX-repo master:gh-pages
exec: fatal: could not read Username for 'https://github.enterprisename.com': No such device or address
```
Is there a way I can fix it?

Thank you!

**Comment by wuweiweiwu** [comment]
@daituzhang I think you need to set a valid `gitUsername` and `gitEmail` 

Hope that helps!

**Comment by hipstersmoothie** [comment]
@daituzhang did @wuweiweiwu's comment help you out? Closing in 1 month if no reponse

**Comment by inside** [comment]
I noticed storybook-deployer doesn't play well with github entreprise and tokens:
https://github.com/storybooks/storybook-deployer/blob/fe6c77621ec0aa033de569e54bc10e9a6499d811/bin/storybook_to_ghpages#L63

It adds the token only if your origin's host is `github.com`. As in your case it's `github.enterprisename.com`, the token is ignored.

@hipstersmoothie would you be interested in a PR solving this github enterprise case?

(I'm on github enterprise too).

**Comment by hipstersmoothie** [comment]
@inside if you have a fix feel free to make a PR 👍

**Comment by inside** [comment]
@hipstersmoothie @daituzhang I found a solution that doesn't require to add Github Enterprise specific code to this program and I think it's better not to be coupled.

I've generated a pair of ssh keys, added the public key (aka deploy keys) in my Github Enterprise repository setting (check read/write access) and added the private key in the travis setting (under the SSH key section) of the repository it is linked to.

[See the documentation for github](https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys).

This means travis can now be recognized by github enterprise and can do git operations.

Best,

**Comment by Eunanibus** [comment]
@inside This wasn't a clear path for Github actions. I'm still running into the `could not read Username for 'https://github.com': No such device or address` problem for GH enterprise. In my case, the GH action itself is initiating the publish action.

If I want my GH action itself to push to a branch, what's the method for this?
