### ISSUE TITLE
Feature request: 404 that redirects to the index

### ISSUE THREAD

**Issue by dgreene1** [storybookjs/storybook-deployer#83]
It seems that the default deploy pushes to the `gh-pages` branch and that the deploy is successful; however, if go to `mydomain.github.com/mylibrary` I get a 404 but if I go to `mydomain.github.com/mylibrary/index.html` I get the storybook page.

So one method (i.e. hack) to get around this is to have a 404.html page that redirects to the index.html page. Perhaps this plugin could automatically deploy a 404 page if configured via a `--fourOhFour 404.html` cli argument.

If there's a more nuanced way to fix this, I'm all ears. :)

**Comment by hipstersmoothie** [comment]
I think this would be a good thing to add. Will review and merge any PRs

**Comment by JackHowa** [comment]
I saw the same behavior

**Comment by tristanmarsh** [comment]
I came here to say I was experiencing this behaviour for up to 1 hour after initial publish. But it no longer seems to be an issue.
Initially `[https://tristanmarsh.github.io/utils/](https://tristanmarsh.github.io/utils/) => "404
There isn't a GitHub Pages site here."

Is this a persistent issue for everyone? I'm thinking it may have more to do with the provisioning of a new GH Page.

**Comment by dgreene1** [comment]
Agree with @tristanmarsh. I’ll close this. Someone can update the readme if they’d like but I’m super duper busy right now. Closing in the meantime.
